### ISSUE TITLE
jira collector logged query error

### ISSUE THREAD

**Issue by hongluovz** [capitalone/Hygieia#276]
I installed a new copy of Hygieia with latest from master branch. 

The problem I reported via issue #220 has been fixed, however I got this error from Jira server response:
"400 Bad Request
{"errorMessages":["Error in the JQL Query: Expecting operator but got '&'. The valid operators are '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' and 'IS NOT'. (line 1, character 12)"],"errors":{}}
com.google.api.client.http.HttpResponseException: 400 Bad Request
{"errorMessages":["Error in the JQL Query: Expecting operator but got '&'. The valid operators are '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' and 'IS NOT'. (line 1, character 12)"],"errors":{}}"

Please see the collector output below:

"016-01-15 11:45:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-01-15 11:45:00,021 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-01-15 11:45:00,044 INFO  c.c.d.d.j.s.c.BaseConnectionImpl - Jira HttpRequestFactory has been generated successfully
2016-01-15 11:45:00,044 INFO  c.c.d.d.j.s.c.ApiPropertiesSupplier - USER-AGENT-HDR:  [SYSTEM INFO HEADER FOR JIRA API TRANSACTION: User Name of System: oracle; Main Application Jar: /apps/opt/tools/Hygieia/jira_feature_collector/target/jira_feature_collector_jar]
2016-01-15 11:45:00,101 INFO  c.c.d.d.j.s.c.GetResponseBuilderImpl - Jira web response message has been successfully generated and transformed
2016-01-15 11:45:00,189 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :0.145286611 seconds to update
2016-01-15 11:45:00,195 INFO  c.c.d.d.j.s.c.BaseConnectionImpl - Jira HttpRequestFactory has been generated successfully
2016-01-15 11:45:00,196 INFO  c.c.d.d.j.s.c.ApiPropertiesSupplier - USER-AGENT-HDR:  [SYSTEM INFO HEADER FOR JIRA API TRANSACTION: User Name of System: oracle; Main Application Jar: /apps/opt/tools/Hygieia/jira_feature_collector/target/jira_feature_collector_jar]
2016-01-15 11:45:00,226 INFO  c.c.d.d.j.s.c.GetResponseBuilderImpl - Jira web response message has been successfully generated and transformed
2016-01-15 11:45:00,265 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Process took :0.069263381 seconds to update
2016-01-15 11:45:00,272 INFO  c.c.d.d.j.s.c.BaseConnectionImpl - Jira HttpRequestFactory has been generated successfully
2016-01-15 11:45:00,273 INFO  c.c.d.d.j.s.c.ApiPropertiesSupplier - USER-AGENT-HDR:  [SYSTEM INFO HEADER FOR JIRA API TRANSACTION: User Name of System: oracle; Main Application Jar: /apps/opt/tools/Hygieia/jira_feature_collector/target/jira_feature_collector_jar]
2016-01-15 11:45:00,273 INFO  c.c.d.d.j.s.c.GetResponseBuilderImpl - getResponse: url = http://onejira.verizon.com/rest/api/2/search?jql=updatedDate%3E%3D'2015-10-31%2023:58'%20AND%20issueType%3D''%20ORDER%20BY%20updated&maxResults=1000&startAt=0
2016-01-15 11:45:00,283 ERROR c.c.d.d.j.s.c.GetResponseBuilderImpl - There was a problem connecting to Jira with a given query:
400 Bad Request
{"errorMessages":["Error in the JQL Query: Expecting operator but got '&'. The valid operators are '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' and 'IS NOT'. (line 1, character 12)"],"errors":{}}
com.google.api.client.http.HttpResponseException: 400 Bad Request
{"errorMessages":["Error in the JQL Query: Expecting operator but got '&'. The valid operators are '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' and 'IS NOT'. (line 1, character 12)"],"errors":{}}
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065) ~[google-http-client-1.14.1-beta.jar!/:1.14.1-beta]
        at com.capitalone.dashboard.datafactory.jira.sdk.connector.GetResponseBuilderImpl.getResponse(GetResponseBuilderImpl.java:66) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.datafactory.jira.JiraDataFactoryImpl.getPagingQueryResponse(JiraDataFactoryImpl.java:170) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.story.FeatureDataClientSetupImpl.updateObjectInformation(FeatureDataClientSetupImpl.java:95) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:431) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:108) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:25) [jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
2016-01-15 11:45:00,283 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - Unexpected error in Jira paging request of java.lang.NullPointerException
[null]
2016-01-15 11:45:00,283 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :0.011526326 seconds to update
2016-01-15 11:45:00,284 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished"

Thanks

**Comment by amp5208** [comment]
Thank you for reaching out regarding your Jira collector question.  There was a recent update with the newest master of the code which requires that you add the following 3 properties to your Jira properties file, depending on your specific Jira instance's configuration:

<pre>
. . .
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=7
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
. . .
</pre>

Please let me know if after providing the correct values for these properties you are still having the issue noted above.

**Comment by smsuresh** [comment]
@amp5208 Do you've any doc on how to populate the above values..
Also, what kind of JIRA tickets should i take for finding those values..
I've populated as per the advice in comment, but not seeing any tickets reflected ..
Seeing only Epics listed in the dashboard..

----------------------
Below is the log i notice



2016-01-25 11:33:01,013 INFO  c.c.d.d.j.s.c.GetResponseBuilderImpl - getResponse: url = http://jira12.abcd.com/rest/api/2/search?jql=updatedDate%3E%3D'2016-01-25%2005:34'%20AND%20issueType%3D'10000'%20ORDER%20BY%20updated&maxResults=1000&startAt=1000
2016-01-25 11:33:01,106 INFO  c.c.d.d.j.s.c.GetResponseBuilderImpl - Jira web response message has been successfully generated and transformed
2016-01-25 11:33:01,107 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :0.227836893 seconds to update
2016-01-25 11:33:01,107 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished

**Comment by amp5208** [comment]
@smsuresh , The doc is only the properties file notes and the same that would be copied into the README.md file of the collector.  Would you suggest something more robust?

The log clearly is indicated a successful response from Jira and data translation - this much is a good thing.  However, please confirm the following:

 - Is your story issue type value truly "10000" for your instance?
 - What is the custom attribute used as reference by your Jira instance for "sprint" data?  It will be prefixed by the following package name content in a REST call:  <strong>com.atlassian.greenhopper.service.sprint.Sprint</strong>.  It will look something like this:  <em>customfield_10007</em>
 - For a given team that you are validating against, are you sure of the following:  A) Stories with valid time estimates have been set on issues in Jira, B) To a given project in Jira, an <strong>active</strong> Sprint is present with valid stories assigned therein.

Please confirm and provide the details above for analysis.

**Comment by smsuresh** [comment]
@amp5208   Pasting you the contents from JIRA, can you help to verify them..





[{"self":"https://abcd.com/rest/api/2/issuetype/3","id":"3","description":"A task that needs to be done.","iconUrl":"https://abcd.com/images/icons/issuetypes/task.png","name":"Task","subtask":false},{"self":"https://abcd.com/rest/api/2/issuetype/10000","id":"10000","description":"The sub-task of the issue","iconUrl":"https://abcd.com/download/resources/com.atlassian.jira-core-project-templates:jira-issuetracking-item/subtask_alternate.png","name":"Sub-Task","subtask":true},{"self":"https://abcd.com/rest/api/2/issuetype/9","id":"9","description":"Created by JIRA Agile - do not edit or delete. Issue type for a user story.","iconUrl":"https://abcd.com/secure/viewavatar?size=xsmall&avatarId=13031&avatarType=issuetype","name":"Story","subtask":false,"avatarId":13031},{"self":"https://abcd.com/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://abcd.com/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},{"self":"https://abcd.com/rest/api/2/issuetype/8","id":"8","description":"Created by JIRA Agile - do not edit or delete. Issue type for a big user story that needs to be broken down.","iconUrl":


--------------------------


r\n}\r\n\r\n{code}","customfield_10131":null,"timetracking":{},"attachment":[],"aggregatetimeestimate":null,"summary":"USP - Deliver, Collect, Verify and Store IVP results.","creator":{"self":"https://abcd.com/rest/api/2/user?username=agilePM","name":"agilePM","key":"agilePM","emailAddress":"agilePM.@mycompany.com","avatarUrls":{"48x48":"https://abcd.com/secure/useravatar?ownerId=agilePM&avatarId=12530","24x24":"https://abcd.com/secure/useravatar?size=small&ownerId=agilePM&avatarId=12530","16x16":"https://abcd.com/secure/useravatar?size=xsmall&ownerId=agilePM&avatarId=12530","32x32":"https://abcd.com/secure/useravatar?size=medium&ownerId=agilePM&avatarId=12530"},"displayName":" agilePM Singh","active":true,"timeZone":"Asia/Kolkata"},"subtasks":[],"customfield_10360":["com.atlassian.greenhopper.service.sprint.Sprint@5d21e9a8[id=252,rapidViewId=175,state=CLOSED,name=Sprint 2,startDate=2016-01-07T07:28:36.540-05:00,endDate=2016-01-20T07:28:00.000-05:00,completeDate=2016-01-25T07:57:54.954-05:00,sequence=252]","com.atlassian.greenhopper.service.sprint.Sprint@12433d17[id=259,rapidViewId=173,state=ACTIVE,name=Sprint 3,startDate=2016-01-25T08:00:51.577-05:00,endDate=2016-02-07T08:00:00.000-05:00,completeDate=<null>,sequence=253]"],"customfield_12462":"1.0","reporter":{"self":"https://abcd.com/rest/api/2/user?username=agilePM","name":"agilePM","key":"agilePM","emailAddress":"agilePM.@mycompany.com","avatarUrls":{"48x48":"https://abcd.com/secure/useravat

---------------------------------

**Comment by smsuresh** [comment]
config has


feature.jiraIssueTypeId=10000
feature.jiraSprintDataFieldName=customfield_10360
feature.jiraEpicIdFieldName=customfield_11560

######################
#Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

#StartDate
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2015-01-01T00:00:00.000



----------------------------------------------------


CONSOLE LOG SHOWS


2016-02-05 06:43:32,947 INFO  com.capitalone.dashboard.Application - Started Application in 3.825 seconds (JVM running for 4.654)
2016-02-05 06:44:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-02-05 06:44:00,005 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-02-05 06:44:00,037 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Beginning collection of team data at Fri Feb 05 06:44:00 UTC 2016
2016-02-05 06:44:00,982 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :0.944462087 seconds to update
2016-02-05 06:44:01,120 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Beginning collection of project data at Fri Feb 05 06:44:01 UTC 2016
2016-02-05 06:44:03,488 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Process took :2.368069915 seconds to update
2016-02-05 06:44:03,601 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Beginning collection of feature data at Fri Feb 05 06:44:03 UTC 2016
2016-02-05 06:44:05,542 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - Unexpected error in Jira paging request of java.lang.NullPointerException
[null]
2016-02-05 06:44:05,544 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :1.942526668 seconds to update
2016-02-05 06:44:05,544 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished
2016-02-05 06:45:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-02-05 06:45:00,005 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-02-05 06:45:00,011 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Beginning collection of team data at Fri Feb 05 06:45:00 UTC 2016
2016-02-05 06:45:00,272 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :0.26081698 seconds to update
2016-02-05 06:45:00,395 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Beginning collection of project data at Fri Feb 05 06:45:00 UTC 2016
2016-02-05 06:45:01,847 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Process took :1.452020439 seconds to update
2016-02-05 06:45:01,858 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Beginning collection of feature data at Fri Feb 05 06:45:01 UTC 2016
2016-02-05 06:45:03,016 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - Unexpected error in Jira paging request of java.lang.NullPointerException



-------------------------------------------------------------

**Comment by smsuresh** [comment]
Still no data in the Hygieia console..

**Comment by smsuresh** [comment]
@amp5208   or ANYONE  @tabladrum 

Can you please help with this..

**Comment by smsuresh** [comment]
@timgifford  @msabramo @hongluovz

**Comment by smsuresh** [comment]
No proper assistance by Hygieia team. Till now i did not see any dashboard with all the contents as mentioned in Your home page/publishings.

**Comment by tabladrum** [comment]
That's sad. Checking in an hour.

**Comment by amp5208** [comment]
@smsuresh , I apologize for the delay in our being able to directly help you faster.  For transparency, there are two factors that have made it difficult to help resolve your issue:

 - Your issue appeared to be related to property file settings, that are custom to your internal instance of Jira (similar to this issue's resolution statement: https://github.com/capitalone/Hygieia/issues/220 - note the new state after the property file updates in the next bullet)
 - There is an existing issue noted with the Feature widget related to a bad merge ( https://github.com/capitalone/Hygieia/pull/322).  With the widget currently failing, it is increasingly difficult to debug user questions

I am currently in-progress with a fix for this failed merge.  Once resolved, please re-pull and evaluate your use; if you are still having issues after that point, we can provide more useful and accurate hands-on assistance.  @tabladrum , Feel free to chime in.

**Comment by amp5208** [comment]
@smsuresh , Please provide me some more information that would help us better help you:

 - Please run the JiraFeatureCollector while debugging with a break-point on the following class:  <em>FeatureDataClientSetupImpl</em> @ line 99.  Let me know what the object instance "rs" contains at that point
 - On your deployment region, please run the following command (or Windows equivalent) to test connectivity to your Jira instance:  <code>curl https://jira.your.instance.com/status</code>.  Did you receive a timout our a valid Jira status response?

**Comment by smsuresh** [comment]
@tabladrum  Thankyou very much for your attention!
@amp5208   Happy to hear from you!

For point 1 - I 'll  reply shortly
                2 - {"state":"RUNNING"}   is the response for  https://MYjira.com/status
 
               3 -   {
	"self": "https://MYjira.com/rest/api/2/issuetype/10000",
	"id": "10000",
	"description": "The sub-task of the issue",
	"iconUrl": "https://MYjira.com/download/resources/com.atlassian.jira-core-project-templates:jira-issuetracking-item/subtask_alternate.png",
	"name": "Sub-Task",
	"subtask": true
}

**Comment by smsuresh** [comment]
I took the latest code & the latest .properties as per   ( https://github.com/capitalone/Hygieia/tree/master/jira-feature-collector)

Below is the error im seeing now..


2016-03-11 12:43:00,965 INFO  com.capitalone.dashboard.Application - Started Application in 4.125 seconds (JVM running for 5.519)
2016-03-11 12:44:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-03-11 12:44:00,010 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-03-11 12:44:00,101 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Beginning collection of team data at Fri Mar 11 12:44:00 UTC 2016
2016-03-11 12:44:01,527 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(401), errorCollections=[]}
2016-03-11 12:44:01,527 ERROR c.c.d.c.team.TeamDataClientSetupImpl - The response from Jira was blank or non existant - please check your property configurations
2016-03-11 12:44:01,540 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :1.438551032 seconds to update

**Comment by smsuresh** [comment]
Below is the file..



#Database Name - default is test
spring.data.mongodb.database=dashboard

#Database HostName - default is localhost
spring.data.mongodb.host=localhost

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=dashboarduser

#Database Password - default is blank
spring.data.mongodb.password=1qazxS23

#Collector schedule (required)
feature.cron=0 0/2 * * * *

#Page size for data calls (Jira maxes at 1000)
feature.pageSize=1000

#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
feature.jiraProxyUrl=http://proxy.com
feature.jiraProxyPort=9999

# Trending Query:  Number of days in a sprint (not-required)
feature.sprintDays=60
# Trending Query:  Length of sprint week (not-required)
feature.sprintEndPrior=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
feature.scheduledPriorMin=2

#Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000

#Jira Connection Details
feature.jiraBaseUrl=http://myjira.com/
#64-bit encoded credentials with the pattern username:password
feature.jiraCredentials=Ydjc1NDMzNDpPaG1NdXJ1Z2FuITIzsdsd
#OAuth2.0 token credentials (currently not supported in this version)
feature.jiraOauthAuthtoken=sdfghjkl==
feature.jiraOauthRefreshtoken=sdfagheh==
feature.jiraOauthRedirecturi=uri.this.is.test:uri
feature.jiraOauthExpiretime=234567890987
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide the name value reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:
# https://[your-jira-domain-name]/rest/api/2/issuetype/.  It is listed as
# attribute "name" in the JSON response.
feature.jiraIssueTypeId=Story
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10360
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10660

#Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
feature.deltaStartDate=2015-02-01T00:00:00.000000
feature.masterStartDate=2015-01-01T00:00:00.000000

#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=
feature.doingStatuses[0]=
feature.doneStatuses[0]=

**Comment by amp5208** [comment]
Try this; your property file still seems to have some problems.  Please take not of the comments that I left in this version of the property file for you:

<pre>
feature.pageSize=50

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

# ONLY fill this out if you have a proxy; otherwise, just leave blank
feature.jiraProxyUrl=http://ONLY.ENTER.IF.YOU.HAVE.A.CORPORATE.PROXY
feature.jiraProxyPort=8099

feature.sprintDays=60
feature.sprintEndPrior=7
feature.scheduledPriorMin=2
feature.deltaCollectorItemStartDate=2015-10-01T00:00:00.000000

spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=1qazxS23

# Fill this out with your Jira instance information
feature.jiraBaseUrl=https://YOUR.JIRA.INSTANCE.COM
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=Ydjc1NDMzNDpPaG1NdXJ1Z2FuITIzsdsd
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

# The Issue Type should be the type that references your Jira STORIES.
# The type you provided, 10000, referrs to Sub-Task.  You may have to change
# This value to match what your Jira instance calls "Story".
feature.jiraIssueTypeId=Sub-Task
feature.jiraSprintDataFieldName=customfield_10360
feature.jiraEpicIdFieldName=customfield_10660
feature.cron=0/2 * * * * *

feature.deltaStartDate=2015-10-01T00:00:00.000000
feature.masterStartDate=20015-10-01T00:00:00.000000

# Core Artifacts - THESE SHOULD BE FILLED OUT FOR EVERY CUSTOM STATUS VALUE
# IN YOUR JIRA INSTANCE
feature.todoStatuses[0]=Backlog
feature.todoStatuses[1]=Grooming
feature.todoStatuses[2]=Ready

feature.doingStatuses[0]=In Progress
feature.doingStatuses[1]=Waiting
feature.doingStatuses[2]=In Review
feature.doingStatuses[3]=For Build

feature.doneStatuses[0]=Approved
feature.doneStatuses[1]=Done
feature.doneStatuses[2]=Accepted
</pre>

Additionally, did you run that cURL command from your local machine, or your host instance?  I ask because if the Jira instance that you are trying to communicate with is within your company's restricted domains or behind a strict firewall, you may not be able to communicate with it directly.  I recommend hitting a non production instance of Jira for a non-production deployment region of Hygieia.  Please confirm.

**Comment by smsuresh** [comment]
@amp5208 Awesome! Though it's weekend i'll go to office shortly just for this & share you the findings! ! 
Thankyou very much!!

**Comment by smsuresh** [comment]
Yes, curl is working, no firewall issue either

**Comment by smsuresh** [comment]
[config details.docx](https://github.com/capitalone/Hygieia/files/170408/config.details.docx)

**Comment by smsuresh** [comment]
2016-03-12 12:58:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-03-12 12:58:00,008 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-03-12 12:58:00,027 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Beginning collection of team data at Sat Mar 12 12:58:00 UTC 2016
2016-03-12 12:58:00,029 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.client.team.TeamDataClientSetupImpl.updateObjectInformation(TeamDataClientSetupImpl.java:85) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:130) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:99) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:26) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_31]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]



---------------------------

Above is the error now,  Attached my properties details for your reference,
I believe my configuration is correct.. Can you please help with this..

**Comment by amp5208** [comment]
Based on the following error stack trace:

<pre>
java.lang.NullPointerException: null
at com.capitalone.dashboard.client.team.TeamDataClientSetupImpl.updateObjectInformation(TeamDataClientSetupImpl.java:85) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
</pre>

I can assume that the issue is coming from the following logical evaluation in the code:

<pre>
        if (!this.featureSettings.getJiraProxyUrl().isEmpty()
				&& (this.featureSettings.getJiraProxyPort() != null)) {
			proxyUri = this.featureSettings.getJiraProxyUrl();
			proxyPort = this.featureSettings.getJiraProxyPort();
		}
</pre>

please make sure that your have the Jira proxy values at least set to blank in your property file if you do not use a proxy; e.g.:

<pre>
...
feature.jiraProxyUrl=
feature.jiraProxyPort=
...
</pre>

This should get you past this error response.  However, a null pointer should not be being thrown here anyway; I will look into this and push a fix; I will tag the pull request here once it is ready for merge and review, for transparency.

**Comment by smsuresh** [comment]
@amp5208   Thankyou very much, Will modify accordingly & share the findings.

**Comment by smsuresh** [comment]
Regarding the array values.. Actually i populated the "id"s i see in our jira/status  json response. I've attached that also in my previous comment.  Do you mind verifying that once.

**Comment by smsuresh** [comment]
No luck..  Below is the response now..
-------------



2016-03-15 04:55:15,123 INFO  com.capitalone.dashboard.Application - Started Application in 3.922 seconds (JVM running for 5.394)
2016-03-15 04:56:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-03-15 04:56:00,018 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-03-15 04:56:00,116 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Beginning collection of team data at Tue Mar 15 04:56:00 UTC 2016
2016-03-15 04:56:01,555 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(401), errorCollections=[]}
2016-03-15 04:56:01,556 ERROR c.c.d.c.team.TeamDataClientSetupImpl - The response from Jira was blank or non existant - please check your property configurations
2016-03-15 04:56:01,566 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :1.449190502 seconds to update

**Comment by amp5208** [comment]
@smsuresh , again, i want to apologize for the time it is taking to get you up and running... All of your recent errors in this thread suggest a bad property configuration somewhere.

In particular, this error is valid and is describing a Jira Unauthorized exception (HTTP 401) :  https://answers.atlassian.com/questions/29623409/error-message-401-while-trying-to-get-issue.  Please validate your Jira credentials and authorizations with those credentials with your system administrator and check back; for Hygieia, you should be using an account that does not expire, and one that has full read permissions of all projects in Jira.

**Comment by smsuresh** [comment]
@amp5208 Thankyou very much!!
Now i say, "Hygieia is awesome" & you too !! :+1: 

Im getting all details ( sprint, days, issues,) but stil getting  0 0 0 for (total, wip,done)  - can you please tell what could be the issue!!

**Comment by amp5208** [comment]
That's great! :D   The "0 0 0" response could be for a couple of things regarding either how you setup the status mapping portion (described here:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-196324494), or simply how your Jira implementation is configured. Please first validate your status mappings for your Jira installation.

Secondly, our team noticed an issue with the database property configurations for the feature collectors the other day.  Not a code problem, just a bad property set on my part - I will fix in my next commit.  For you, however, simply change the section in your database property configuration at the following place:

<pre>
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=[USERNAME]
spring.data.mongodb.password=[PASSWORD]
</pre>

... change to be this:

<pre>
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=[USERNAME]
dbpassword=[PASSWORD]
</pre>

There is a chance that essentially your collectors are saving data in a different database than is being used/configured by Hygieia, overall, because of this missing setting.  Please try and verify.

**Comment by smsuresh** [comment]
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=[USERNAME]
dbpassword=[PASSWORD]

This change is working fine..

But still not getting, how exactly to populate Array values for "statuses".. 0 0 0 still..

**Comment by smsuresh** [comment]
Below are the property values..



feature.todoStatuses[0]=Open
feature.todoStatuses[1]=Reopened
feature.todoStatuses[2]=More Info Required
feature.todoStatuses[3]=To Do

feature.doingStatuses[0]=In Progress
feature.doingStatuses[1]=Resolved
feature.doingStatuses[2]=RTT
feature.doingStatuses[3]=BigTrouble
feature.doingStatuses[4]=Backlog
feature.doingStatuses[5]=Testing
feature.doingStatuses[6]=Dev - In Progress
feature.doingStatuses[7]=QA - In Progress

feature.doneStatuses[0]=Done
feature.doneStatuses[1]=Closed

**Comment by smsuresh** [comment]
Can you refer the [https://github.com/capitalone/Hygieia/files/170408/config.details.docx](my prop) and help to correc the config error, if any for status

**Comment by amp5208** [comment]
@smsuresh , actually, your updated status mappings above should be working fine.  In that case, the problem now lies upstream from the collector, especially if you are seeing that data is being populated in your _feature_ collection of your database.  Please give me more details of the upstream configuration.

_Note:  I am using a Mac and am unable to open the docx file contents that you have provided.  However, as mentioned above, I believe your properties are now good if you are collecting Jira data successfully._

**Comment by smsuresh** [comment]
[status.txt](https://github.com/capitalone/Hygieia/files/179455/status.txt)
@amp5208  Attached in text format, can you please help to verify the status part alone.

**Comment by kv113813** [comment]
I also have same issues, I am getting the project name but shows:
Scope: Jira - Dashboard
Sprint: [No Sprint Available] [N/A]
Total
0
WIP
0
Done
0

**Comment by smsuresh** [comment]
@kv113813   Do you see epic/Issue details below that..

**Comment by amp5208** [comment]
@smsuresh , Your statuses seem to be mapped correctly... confirm if the following is correct within your Jira instance:

 - The Project is associated to a single Sprint
 - The Sprint for that project is Active (i.e., today's date lies within the Sprint's timebox)
 - Active stories are assigned to the given Sprint and Project
 - Stories are using the "Remaining Estimate" out-of-the-box estimate field for time tracking

If you are no longer seeing collection errors and property configurations are correct, I can only assume that your Jira implementation is not following Hygieia's out-of-the-box assumptions of use.

**Comment by amp5208** [comment]
@kv113813:  Can you confirm that you are seeing any collector-level errors?  If so, please refer to this section of this forum to update your property file configurations:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-196324494.  If not, please validate my statement above:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-199388906

**Comment by kv113813** [comment]
@amp5208 @smsuresh I do not see any error at collector side, Let me validate your pointers provided above.

**Comment by amp5208** [comment]
@kv113813 , Please let me know if you have any further open issues regarding this forum.  If not, I will have the issue closed.

**Comment by kv113813** [comment]
I still have the same issue, I am getting the project name (Jira - Dashboard) but no other details:
Scope: Jira - Dashboard
Sprint: [No Sprint Available] [N/A]
Total
0
WIP
0
Done
0

I suspect on Epic & sprint field id/name. Is there a way to precisely check this since I see lots of "customfield_xxxxX" in json

**Comment by smsuresh** [comment]
Better take the latest code again n try. Use some online json tool to find custom values correctly

**Comment by amp5208** [comment]
:+1:  to @smsuresh 's comment.  To add, unfortunately the only way to validate the custom_field attributes from Jira is to manually open an issue that you know is using the fields, and verify the field name that stores relevant content from the Story-type issue.

**Comment by amp5208** [comment]
@smsuresh, @kv113813  , Please verify that your issue has been resolved so that this issue can be closed.
@tabladrum , unless otherwise mentioned by the noted customers, this issue should be closed, as customers' questions were answered and confirmed resolved by at least one of them.

**Comment by tanaysh7** [comment]
Facing same issue of No Stats. IssueTypeId I see in a prop file of this thread is Sub-Task, Is it supposed to be Sub-Task if there is one available in Jira?

**Comment by tabladrum** [comment]
Can you use the latest from master and reopen is the issue is still there?
