### ISSUE TITLE
Jira collector -  Unexpected error in Jira paging request of java.lang.NullPointerException [null]

### ISSUE THREAD

**Issue by rodrigosiviero** [capitalone/Hygieia#656]
Hi,

I have an instance of Hygieia running @ AWS using docker-compose and I was not able to configure properly the Jira Collector, it's throwing me the paging request NullPointer error, I tried to follow the other related topics open here but nothing works.

![image](https://cloud.githubusercontent.com/assets/19693642/16383742/d039b90c-3c5c-11e6-9204-a66f5647263f.png)

I have a brand new Jira trial instance with One Epic, One Story and One Active Sprint.

I'm Adding the files here, if someone could please help me. (cc: @amp5208 )

Jira Issues json(this is where I've got the customfields.)
[issues.txt](https://github.com/capitalone/Hygieia/files/335089/issues.txt)

Jira Statuses json
[status.txt](https://github.com/capitalone/Hygieia/files/335100/status.txt)

Hygieia Collector properties

[https://gist.github.com/rodrigosiviero/ac1b0ee20f768df30199b8bec9f5bb79](url)

I'm available @ gitter.im if anyone willing to help me !

Thank you guys.

**Comment by MarkRx** [comment]
I have been unable to get the jira collector working successfully either. Certain situations seem to make it fail. I am working on code changes right now to fix what is happening to me. Should be done within a week or so.

**Comment by rodrigosiviero** [comment]
@MarkRx I was testing this again with your code and now I'm not getting null pointer exception but it does not show anything -

```
2016-07-13 19:14:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:14:00,005 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-13 19:14:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:14:00,653 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-13 19:14:01,028 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-13 19:14:01,528 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-13 19:14:01,528 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-13 19:15:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-13 19:15:00,023 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:15:00,023 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-13 19:15:00,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:15:00,625 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-13 19:15:00,977 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-13 19:15:01,334 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-13 19:15:01,334 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-13 19:16:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-13 19:16:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:16:00,003 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-13 19:16:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:16:00,576 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-13 19:16:01,019 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-13 19:16:01,415 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-13 19:16:01,415 INFO  c.c.d.collector.CollectorTask - Finished                         1s

```

Any idea?

**Comment by MarkRx** [comment]
What version of jira are you running?

Add logging to your spring config to help track down what is going on. Either temporarily throw it into jira-properties-builder.sh or override the command for docker compose and point to a mounted properties file.

```
logging.level.com.capitalone.dashboard.collector=DEBUG
logging.level.com.capitalone.dashboard=DEBUG
```

double check jiraIssueTypeId. For me it is Story but it could be different depending on the name of your 'Story' issue type. Also verify you are hitting the right custom fields.

**Comment by rodrigosiviero** [comment]
Hi @MarkRx , I'm using the Jira cloud trial:

Version	1000.148.2
Build Number	100005

Sprint custom field:
customfield_10019: [
"com.atlassian.greenhopper.service.sprint.Sprint@1410509[id=1,rapidViewId=1,state=ACTIVE,name=PROJ Sprint 1,goal=,startDate=2016-07-13T12:49:04.732-03:00,endDate=2016-07-27T12:49:00.000-03:00,completeDate=<null>,sequence=1]"
],

Epic custom field:
customfield_10017: "Test-Epic-1",


I'm kinda of confused on how to get the customfields, specially the Epic one, not sure if I'm doing it right.

DEBUG:

```
2016-07-13 19:40:00,023 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:40:00,024 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-13 19:40:00,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:40:00,024 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-13 19:40:00,590 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-13 19:40:00,596 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-13 19:40:00,596 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-13 19:40:00,963 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-13 19:40:00,970 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-13 19:40:00,970 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-13 19:40:00,974 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-13 19:40:01,329 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0
2016-07-13 19:40:01,330 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 355 ms
2016-07-13 19:40:01,330 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-13 19:40:01,330 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-13 19:41:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-13 19:41:00,004 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:41:00,005 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-13 19:41:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-13 19:41:00,005 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-13 19:41:00,701 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-13 19:41:00,706 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-13 19:41:00,706 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-13 19:41:01,069 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-13 19:41:01,076 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-13 19:41:01,076 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-13 19:41:01,083 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-13 19:41:01,462 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0
2016-07-13 19:41:01,462 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 379 ms
2016-07-13 19:41:01,462 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-13 19:41:01,463 INFO  c.c.d.collector.CollectorTask - Finished                         1s
```

**Comment by MarkRx** [comment]
So the log indicates you are not getting any data back from your REST API call. Have you created stories in jira?

What is the output of the following API call? It's possible Jira Cloud uses different API rest calls like Bitbucket does.

Here is a sample raw API call:
https://hygieiatest.atlassian.net/rest/api/2/search?fields=*all&jql=updatedDate>='2016-04-01 12:00' AND issueType='Story' ORDER BY updated ASC

URL Encoded:
https://hygieiatest.atlassian.net/rest/api/2/search?fields=*all&jql=updatedDate%3E=%272016-04-01%2012:00%27%20AND%20issueType=%27Story%27%20ORDER%20BY%20updated%20ASC

**Comment by rodrigosiviero** [comment]
Hi @MarkRx 

Here's the call:

https://gist.github.com/rodrigosiviero/c10cd03a5df68694c9d3d86084c6138d

**Comment by rodrigosiviero** [comment]
Hi @MarkRx 

Here the result of the advanced query:
https://i.imgur.com/igQGn8R.png

How can I delete the mongodb data for the feature collection?

**Comment by MarkRx** [comment]
You can either use a mongodb tool like robomongo or connect to mongo from the command line. See if the features collection has any documents in it. I don't use the command line too much so if you go that route you will have to find the commands in the manual / google it.

**Comment by gau1991** [comment]
When I set `logging.level.com.atlassian.jira=DEBUG`, I got following stack trace:

```
2016-07-21 09:35:00,327 DEBUG c.a.j.r.c.i.a.AsynchronousHttpClientFactory$MavenUtils - Got the following exception
java.lang.NullPointerException: null
	at java.util.Properties$LineReader.readLine(Properties.java:434) ~[na:1.8.0_91]
	at java.util.Properties.load0(Properties.java:353) ~[na:1.8.0_91]
	at java.util.Properties.load(Properties.java:341) ~[na:1.8.0_91]
	at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory$MavenUtils.getVersion(AsynchronousHttpClientFactory.java:158) ~[jira-rest-java-client-core-2.0.0.jar!/:na]
	at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory$RestClientApplicationProperties.getVersion(AsynchronousHttpClientFactory.java:121) [jira-rest-java-client-core-2.0.0.jar!/:na]
	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.getUserAgent(DefaultHttpClient.java:168) [atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.<init>(DefaultHttpClient.java:139) [atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
	at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:53) [jira-rest-java-client-core-2.0.0.jar!/:na]
	at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35) [jira-rest-java-client-core-2.0.0.jar!/:na]
	at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42) [jira-rest-java-client-core-2.0.0.jar!/:na]
	at com.capitalone.dashboard.datafactory.jira.JiraDataFactoryImpl.<init>(JiraDataFactoryImpl.java:179) [jira-feature-collector.jar!/:2.0.0-SNAPSHOT]
	at com.capitalone.dashboard.client.story.FeatureDataClientSetupImpl.updateObjectInformation(FeatureDataClientSetupImpl.java:92) [jira-feature-collector.jar!/:2.0.0-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:510) [jira-feature-collector.jar!/:2.0.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:26) [jira-feature-collector.jar!/:2.0.0-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2016-07-21 09:35:00,373 DEBUG c.c.d.c.story.StoryDataClientImpl - Size of paged Jira response: 
2016-07-21 09:35:00,373 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - Unexpected error in Jira paging request of java.lang.NullPointerException
[null]
2016-07-21 09:35:00,399 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :0.076373102 seconds to update
2016-07-21 09:35:00,401 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished
```

**Comment by MarkRx** [comment]
@gau1991 that stack trace is from old code. Try doing a fresh build off of master or waiting until the next version is released and published.

**Comment by rodrigosiviero** [comment]
Hi @MarkRx , Thanks for the help but still showing 0,0,0, here's the commands used to clean feature collection:

```
> use dashboard
switched to db dashboard
> show collections
authentication
builds
cloud_instance
cloud_instance_history
cloud_subnetwork
cloud_virtual_network
cloud_volume
code_quality
collector_items
collectors
commits
components
dashboards
feature
pipelines
scope
services
test_results
> db.feature.remove({})
WriteResult({ "nRemoved" : 2 })
```

And here the logs, note that on 2016-07-21 14:27:01,881 it finds the Story

```
2016-07-21 14:25:01,487 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 392 ms
2016-07-21 14:25:01,487 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-21 14:25:01,487 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-21 14:26:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-21 14:26:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:26:00,005 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-21 14:26:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:26:00,005 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-21 14:26:00,626 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:26:00,632 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-21 14:26:00,632 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-21 14:26:01,029 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:26:01,035 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-21 14:26:01,035 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-21 14:26:01,042 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-21 14:26:01,447 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0
2016-07-21 14:26:01,447 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 405 ms
2016-07-21 14:26:01,447 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-21 14:26:01,447 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-21 14:27:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-21 14:27:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:27:00,008 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-21 14:27:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:27:00,008 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-21 14:27:00,664 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:27:00,667 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-21 14:27:00,667 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-21 14:27:01,177 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:27:01,179 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-21 14:27:01,180 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-21 14:27:01,182 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-21 14:27:01,880 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 1 out of 1
2016-07-21 14:27:01,880 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 698 ms
2016-07-21 14:27:01,881 DEBUG c.c.d.c.story.StoryDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:27:01,883 DEBUG c.c.d.c.story.StoryDataClientImpl - [PROJ-1      ] Test-Story-1
2016-07-21 14:27:01,887 DEBUG c.c.d.c.story.StoryDataClientImpl - Processing epic data
2016-07-21 14:27:01,888 DEBUG c.c.d.c.story.StoryDataClientImpl - Processing epic data took 1 ms
2016-07-21 14:27:01,902 INFO  c.c.d.collector.CollectorTask - Story Data              1        0s
2016-07-21 14:27:01,902 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-21 14:28:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-21 14:28:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:28:00,003 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-21 14:28:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:28:00,003 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-21 14:28:00,650 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:28:00,654 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-21 14:28:00,654 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-21 14:28:01,040 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:28:01,043 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-21 14:28:01,043 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-21 14:28:01,046 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-21 14:28:01,409 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0
2016-07-21 14:28:01,409 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 363 ms
2016-07-21 14:28:01,409 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-21 14:28:01,409 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-21 14:29:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-21 14:29:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:29:00,006 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-21 14:29:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:29:00,006 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-21 14:29:00,607 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:29:00,610 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-21 14:29:00,610 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-21 14:29:00,989 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:29:00,992 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-21 14:29:00,992 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-21 14:29:00,994 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-21 14:29:01,377 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0
2016-07-21 14:29:01,377 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 383 ms
2016-07-21 14:29:01,377 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-21 14:29:01,377 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-21 14:30:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-21 14:30:00,028 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:30:00,029 INFO  c.c.d.collector.CollectorTask - https://hygieiatest.atlassian.net
2016-07-21 14:30:00,029 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-21 14:30:00,029 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-07-21 14:30:00,666 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:30:00,675 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-21 14:30:00,675 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-07-21 14:30:01,064 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1
2016-07-21 14:30:01,068 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-21 14:30:01,068 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-07-21 14:30:01,071 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-07-21 14:30:01,472 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0
2016-07-21 14:30:01,473 DEBUG c.c.d.c.story.StoryDataClientImpl - Story information query took 402 ms
2016-07-21 14:30:01,473 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-21 14:30:01,473 INFO  c.c.d.collector.CollectorTask - Finished                         1s

```

**Comment by MarkRx** [comment]
I see. So what is happening is your stories do not have any time tracking data. The "features" list is empty because you have not set epics on your stories.

PR #682 has been merged in. Pull in those changes and build from master. Then wipe the "features" collection in mongo again. Add a new property to your collector properties file called 'feature.jiraStoryPointsFieldName'. Put story points on your stories then determine the custom_xxxxxx field that it is. Finally you will have to reconfigure your jira widget in the dashboard and explicitly set "Story Points" or "Hours". You may have to change it once, save, and change it again to something else and save (aka toggle the field) since this field is new.

`#############################################################################
# In Jira, your instance will have its own custom field created for "story points"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10003`

To get time metrics to show up add time estimates to your story (if enabled) or create story subtasks and add the estimates to those.

To get the features list (epics) to show up add some epics, set them on stories with points assigned, and configure your epics field in your properties.

**Comment by tabladrum** [comment]
I merged the pending PR. Sorry for the delay.

**Comment by rodrigosiviero** [comment]
I'll test asap, thank you guys!!

**Comment by gau1991** [comment]
@MarkRx ,
I just tried the master branch. Jira collector is now working fine. Its also showing data in logs.
```
2016-07-27 10:41:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-27 10:41:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-27 10:41:00,003 INFO  c.c.d.collector.CollectorTask - http://X.X.X.X/
2016-07-27 10:41:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-27 10:41:00,043 INFO  c.c.d.collector.CollectorTask - Team Data               1        0s
2016-07-27 10:41:00,078 INFO  c.c.d.collector.CollectorTask - Project Data            1        0s
2016-07-27 10:41:00,132 INFO  c.c.d.collector.CollectorTask - Story Data              2        0s
2016-07-27 10:41:00,132 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2016-07-27 10:42:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
```

But UI is showing "No Active Iterations". I tired both estimate matric but still not worked.

**Comment by MarkRx** [comment]
That will happen if you don't have any active sprints. The sprints will be bound by start and end dates.

**Comment by gau1991** [comment]
@MarkRx 
Sprint is already set to active. Also I verified that Sprint is bound by Start and end dates.

**Comment by MarkRx** [comment]
You might need to wipe the scope and feature collections along with collector_items that have the class 'ScopeOwnerCollectorItem' since the data has come from several different versions of the application now. Also verify your sprint configuration is correct and you are pulling that data from the right field. Create a new dashboard too just in case that needs to be fresh as well.

> db.getCollection('collector_items').find({'_class': 'com.capitalone.dashboard.model.ScopeOwnerCollectorItem'})

If creating a new dashboard and wiping existing data doesn't work (in case something was incompatible after an upgrade) I suggest looking at the mongo documents representing your data and viewing the REST API call the UI makes. When in a browser you can open a browsers development console and turn on network tracking to see the REST calls that are made to the API layer. That will take you to FeatureController.java with a url of something like url/iteration/{teamid}. Following the code will bring you to getCurrentSprintDetail in FeatureServiceImpl which uses the following mongo query:

`	@Query(value = "{'sTeamID' : ?0 , 'isDeleted' : 'False', $and : [{'sSprintID' : {$ne : null}} , {'sSprintBeginDate' : {$lte : ?1}} , {'sSprintEndDate' : {$gte : ?1}}]}, $orderby: { 'sStatus' :-1 }", fields = "{'sSprintID' : 1, 'sSprintName' : 1,'sSprintBeginDate' : 1, 'sSprintEndDate' : 1}")`

I suspect that query isn't returning any data.

**Comment by gau1991** [comment]
@MarkRx My setup is complete fresh and created using master branch of Hygieia. Although its showing data into log, its not adding any data into MongoDB. Your query is also not returning any data. 

Just for into, I have one active sprint which is bound by start and end data, One Active Epic added into Sprint, and Active Story in the Sprint has story point set and estimated time is also set.

**Comment by MarkRx** [comment]
If the log with debugging shows data but your database does not have any then there must be something wrong with your configuration. If so please open a new issue as I think the issue of this thread has been solved.

**Comment by rodrigosiviero** [comment]
Hi @MarkRx 

Yes, this error has been resolved.

Still not getting Features in progress, iteration and Kanban it's like this:

![image](https://cloud.githubusercontent.com/assets/19693642/17368610/34344ef6-596b-11e6-9088-7f4635b48fec.png)


@gau1991 is this the same problem? Maybe open a new issue?

**Comment by gau1991** [comment]
Hello Guys, Tried yesterday on fresh machine again. It worked very well. The issue was with configuration. I needed to set following values in configuration file.
```
feature.todoStatuses[0]=
feature.doingStatuses[0]=
feature.doneStatuses[0]=
``` 

So as it is working this issue can be closed.

**Comment by MarkRx** [comment]
The Kanban view currently shows items that are not assigned to a sprint. I have it on my backlog to fix that as issues without a sprint does not necessary imply kanban (#678). 

Features in progress will show epics that have stories that are being worked on. In order for it to show up your epics configuration must be setup, you must have active epics, you must have stories assigned to epics, and you must have stories assigned to epics that are in progress.

**Comment by satishc1** [comment]
Closed. The feature widget now has an option to display metrics based on the number of tickets instead of estimates. This is for setups that do not use estimates.
Functionality merged in https://github.com/capitalone/Hygieia/pull/1054 Use latest codebase. You’ll also need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137
